<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Empleado;

class EmpleadoSeeder extends Seeder
{
    public function run(): void
    {
        $empleados = [
            [
                'nombre' => 'Carlos',
                'apellido' => 'Ramirez',
                'correo' => 'carlos.ramirez@oxi.com',
                'telefono' => '5512345678',
                'domicilio' => 'Iztapalapa, CDMX',
                'fecha_inicio' => '2021-03-15',
                'estado' => 'Activo',
                'foto' => null,
                'puesto' => 'Supervisor',
                'departamento' => 'Inventario',
                'banco' => 'BBVA',
                'numero_cuenta' => '012345678901',
                'grado_estudios' => 'Licenciatura',
                'especialidad' => 'Logística',
                'tipo_contrato' => 'Indefinido',
                'antiguedad' => '5 años 1 mes',
                'nss' => '12345678901',
                'rfc' => 'RARC900101ABC',
            ],
            [
                'nombre' => 'Fernanda',
                'apellido' => 'Lopez',
                'correo' => 'fernanda.lopez@oxi.com',
                'telefono' => '5523456789',
                'domicilio' => 'Nezahualcóyotl, EdoMex',
                'fecha_inicio' => '2022-06-10',
                'estado' => 'Activo',
                'foto' => null,
                'puesto' => 'Auxiliar RH',
                'departamento' => 'Recursos Humanos',
                'banco' => 'Santander',
                'numero_cuenta' => '223344556677',
                'grado_estudios' => 'Licenciatura',
                'especialidad' => 'Administración',
                'tipo_contrato' => 'Indefinido',
                'antiguedad' => '3 años 10 meses',
                'nss' => '22345678901',
                'rfc' => 'LOPF920202DEF',
            ],
            [
                'nombre' => 'Miguel',
                'apellido' => 'Torres',
                'correo' => 'miguel.torres@oxi.com',
                'telefono' => '5534567890',
                'domicilio' => 'Ecatepec, EdoMex',
                'fecha_inicio' => '2020-01-08',
                'estado' => 'Activo',
                'foto' => null,
                'puesto' => 'Desarrollador',
                'departamento' => 'Sistemas',
                'banco' => 'Banorte',
                'numero_cuenta' => '334455667788',
                'grado_estudios' => 'Ingeniería',
                'especialidad' => 'Software',
                'tipo_contrato' => 'Indefinido',
                'antiguedad' => '6 años 4 meses',
                'nss' => '32345678901',
                'rfc' => 'TORM930303GHI',
            ],
            [
                'nombre' => 'Andrea',
                'apellido' => 'Mendoza',
                'correo' => 'andrea.mendoza@oxi.com',
                'telefono' => '5545678901',
                'domicilio' => 'Coyoacán, CDMX',
                'fecha_inicio' => '2023-02-11',
                'estado' => 'Activo',
                'foto' => null,
                'puesto' => 'Vendedora',
                'departamento' => 'Ventas',
                'banco' => 'HSBC',
                'numero_cuenta' => '445566778899',
                'grado_estudios' => 'Preparatoria',
                'especialidad' => 'Atención al cliente',
                'tipo_contrato' => 'Temporal',
                'antiguedad' => '2 años 2 meses',
                'nss' => '42345678901',
                'rfc' => 'MEAA940404JKL',
            ],
            [
                'nombre' => 'Luis',
                'apellido' => 'Santos',
                'correo' => 'luis.santos@oxi.com',
                'telefono' => '5556789012',
                'domicilio' => 'Tlalnepantla, EdoMex',
                'fecha_inicio' => '2019-09-01',
                'estado' => 'Activo',
                'foto' => null,
                'puesto' => 'Jefe de almacén',
                'departamento' => 'Inventario',
                'banco' => 'BBVA',
                'numero_cuenta' => '556677889900',
                'grado_estudios' => 'Licenciatura',
                'especialidad' => 'Cadena de suministro',
                'tipo_contrato' => 'Indefinido',
                'antiguedad' => '6 años 8 meses',
                'nss' => '52345678901',
                'rfc' => 'SALU950505MNO',
            ],
            [
                'nombre' => 'Patricia',
                'apellido' => 'Vega',
                'correo' => 'patricia.vega@oxi.com',
                'telefono' => '5567890123',
                'domicilio' => 'Benito Juárez, CDMX',
                'fecha_inicio' => '2021-11-20',
                'estado' => 'Activo',
                'foto' => null,
                'puesto' => 'Analista',
                'departamento' => 'Sistemas',
                'banco' => 'Scotiabank',
                'numero_cuenta' => '667788990011',
                'grado_estudios' => 'Ingeniería',
                'especialidad' => 'Bases de datos',
                'tipo_contrato' => 'Indefinido',
                'antiguedad' => '4 años 5 meses',
                'nss' => '62345678901',
                'rfc' => 'VEGP960606PQR',
            ],
            [
                'nombre' => 'Ricardo',
                'apellido' => 'Navarro',
                'correo' => 'ricardo.navarro@oxi.com',
                'telefono' => '5578901234',
                'domicilio' => 'Chalco, EdoMex',
                'fecha_inicio' => '2024-01-10',
                'estado' => 'Activo',
                'foto' => null,
                'puesto' => 'Capturista',
                'departamento' => 'Recursos Humanos',
                'banco' => 'Azteca',
                'numero_cuenta' => '778899001122',
                'grado_estudios' => 'Técnico',
                'especialidad' => 'Administración',
                'tipo_contrato' => 'Temporal',
                'antiguedad' => '1 año 3 meses',
                'nss' => '72345678901',
                'rfc' => 'NARR970707STU',
            ],
            [
                'nombre' => 'Diana',
                'apellido' => 'Cruz',
                'correo' => 'diana.cruz@oxi.com',
                'telefono' => '5589012345',
                'domicilio' => 'Xochimilco, CDMX',
                'fecha_inicio' => '2022-08-18',
                'estado' => 'Activo',
                'foto' => null,
                'puesto' => 'Ejecutiva comercial',
                'departamento' => 'Ventas',
                'banco' => 'Banamex',
                'numero_cuenta' => '889900112233',
                'grado_estudios' => 'Licenciatura',
                'especialidad' => 'Mercadotecnia',
                'tipo_contrato' => 'Indefinido',
                'antiguedad' => '3 años 8 meses',
                'nss' => '82345678901',
                'rfc' => 'CRUD980808VWX',
            ],
            [
                'nombre' => 'Jorge',
                'apellido' => 'Flores',
                'correo' => 'jorge.flores@oxi.com',
                'telefono' => '5590123456',
                'domicilio' => 'Naucalpan, EdoMex',
                'fecha_inicio' => '2020-05-30',
                'estado' => 'Inactivo',
                'foto' => null,
                'puesto' => 'Soporte TI',
                'departamento' => 'Sistemas',
                'banco' => 'BBVA',
                'numero_cuenta' => '990011223344',
                'grado_estudios' => 'Ingeniería',
                'especialidad' => 'Redes',
                'tipo_contrato' => 'Indefinido',
                'antiguedad' => '5 años 11 meses',
                'nss' => '92345678901',
                'rfc' => 'FLOJ990909YZA',
            ],
            [
                'nombre' => 'Sofia',
                'apellido' => 'Herrera',
                'correo' => 'sofia.herrera@oxi.com',
                'telefono' => '5511122233',
                'domicilio' => 'Cuautitlán, EdoMex',
                'fecha_inicio' => '2023-07-14',
                'estado' => 'Activo',
                'foto' => null,
                'puesto' => 'Asistente de ventas',
                'departamento' => 'Ventas',
                'banco' => 'Santander',
                'numero_cuenta' => '101112131415',
                'grado_estudios' => 'Licenciatura',
                'especialidad' => 'Comercio',
                'tipo_contrato' => 'Temporal',
                'antiguedad' => '1 año 9 meses',
                'nss' => '10345678901',
                'rfc' => 'HERS000101BCD',
            ],
        ];

        foreach ($empleados as $empleado) {
            Empleado::create($empleado);
        }
    }
}
