<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Employee;
use App\Models\Position;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $employees = [
            [
                'first_name' => 'Carlos',
                'last_name' => 'Ramirez',
                'email' => 'carlos.ramirez@oxi.com',
                'phone' => '5512345678',
                'street' => 'Av. Ermita Iztapalapa',
                'external_number' => '123',
                'internal_number' => 'A',
                'postal_code' => '09000',
                'neighborhood' => 'La Viga',
                'municipality' => 'Iztapalapa',
                'address_state' => 'Ciudad de México',
                'maps_url' => 'https://maps.google.com',
                'start_date' => '2021-04-01',
                'employment_status' => 'Activo',
                'photo' => null,
                'position' => 'Supervisor',
                'department' => 'Inventario',
                'bank' => 'BBVA',
                'account_number' => '012345678901',
                'education_level' => 'Licenciatura',
                'specialty' => 'Logística',
                'contract_type' => 'Indefinido',
                'seniority' => '5 años 1 mes',
                'nss' => '12345678901',
                'rfc' => 'RARC900101ABC',
            ],
            [
                'first_name' => 'Fernanda',
                'last_name' => 'Lopez',
                'email' => 'fernanda.lopez@oxi.com',
                'phone' => '5523456789',
                'street' => 'Calle 1',
                'external_number' => '456',
                'internal_number' => 'B',
                'postal_code' => '09000',
                'neighborhood' => 'San Juan de los Lagos',
                'municipality' => 'Nezahualcóyotl',
                'address_state' => 'Estado de México',
                'maps_url' => 'https://maps.google.com',
                'start_date' => '2022-06-10',
                'employment_status' => 'Activo',
                'photo' => null,
                'position' => 'Auxiliar RH',
                'department' => 'Recursos Humanos',
                'bank' => 'Santander',
                'account_number' => '223344556677',
                'education_level' => 'Licenciatura',
                'specialty' => 'Administración',
                'contract_type' => 'Indefinido',
                'seniority' => '3 años 10 meses',
                'nss' => '22345678901',
                'rfc' => 'LOPF920202DEF',
            ],
            [
                'first_name' => 'Miguel',
                'last_name' => 'Torres',
                'email' => 'miguel.torres@oxi.com',
                'phone' => '5534567890',
                'street' => 'Calle 2',
                'external_number' => '789',
                'internal_number' => 'C',
                'postal_code' => '09000',
                'neighborhood' => 'Ecatepec',
                'municipality' => 'Ecatepec de Morelos',
                'address_state' => 'Estado de México',
                'maps_url' => 'https://maps.google.com',
                'start_date' => '2020-01-08',
                'employment_status' => 'Activo',
                'photo' => null,
                'position' => 'Desarrollador',
                'department' => 'Sistemas',
                'bank' => 'Banorte',
                'account_number' => '334455667788',
                'education_level' => 'Ingeniería',
                'specialty' => 'Software',
                'contract_type' => 'Indefinido',
                'seniority' => '6 años 4 meses',
                'nss' => '32345678901',
                'rfc' => 'TORM930303GHI',
            ],
            [
                'first_name' => 'Andrea',
                'last_name' => 'Mendoza',
                'email' => 'andrea.mendoza@oxi.com',
                'phone' => '5545678901',
                'street' => 'Calle 3',
                'external_number' => '101',
                'internal_number' => 'D',
                'postal_code' => '09000',
                'neighborhood' => 'Coyoacán',
                'municipality' => 'Ciudad de México',
                'address_state' => 'Ciudad de México',
                'maps_url' => 'https://maps.google.com',
                'start_date' => '2023-02-11',
                'employment_status' => 'Activo',
                'photo' => null,
                'position' => 'Vendedora',
                'department' => 'Ventas',
                'bank' => 'HSBC',
                'account_number' => '445566778899',
                'education_level' => 'Preparatoria',
                'specialty' => 'Atención al cliente',
                'contract_type' => 'Temporal',
                'seniority' => '2 años 2 meses',
                'nss' => '42345678901',
                'rfc' => 'MEAA940404JKL',
            ],
            [
                'first_name' => 'Luis',
                'last_name' => 'Santos',
                'email' => 'luis.santos@oxi.com',
                'phone' => '5556789012',
                'street' => 'Calle 4',
                'external_number' => '102',
                'internal_number' => 'E',
                'postal_code' => '09000',
                'neighborhood' => 'Tlalnepantla',
                'municipality' => 'Tlalnepantla de Baz',
                'address_state' => 'Estado de México',
                'maps_url' => 'https://maps.google.com',
                'start_date' => '2019-09-01',
                'employment_status' => 'Activo',
                'photo' => null,
                'position' => 'Jefe de almacén',
                'department' => 'Inventario',
                'bank' => 'BBVA',
                'account_number' => '556677889900',
                'education_level' => 'Licenciatura',
                'specialty' => 'Cadena de suministro',
                'contract_type' => 'Indefinido',
                'seniority' => '6 años 8 meses',
                'nss' => '52345678901',
                'rfc' => 'SALU950505MNO',
            ],
            [
                'first_name' => 'Patricia',
                'last_name' => 'Vega',
                'email' => 'patricia.vega@oxi.com',
                'phone' => '5567890123',
                'street' => 'Av. Benito Juárez',
                'external_number' => '123',
                'internal_number' => 'F',
                'postal_code' => '09000',
                'neighborhood' => 'Roma',
                'municipality' => 'Ciudad de México',
                'address_state' => 'Ciudad de México',
                'maps_url' => 'https://maps.google.com',
                'start_date' => '2021-11-20',
                'employment_status' => 'Activo',
                'photo' => null,
                'position' => 'Analista',
                'department' => 'Sistemas',
                'bank' => 'Scotiabank',
                'account_number' => '667788990011',
                'education_level' => 'Ingeniería',
                'specialty' => 'Bases de datos',
                'contract_type' => 'Indefinido',
                'seniority' => '4 años 5 meses',
                'nss' => '62345678901',
                'rfc' => 'VEGP960606PQR',
            ],
            [
                'first_name' => 'Ricardo',
                'last_name' => 'Navarro',
                'email' => 'ricardo.navarro@oxi.com',
                'phone' => '5578901234',
                'street' => 'Calle 5',
                'external_number' => '103',
                'internal_number' => 'G',
                'postal_code' => '09000',
                'neighborhood' => 'Chalco',
                'municipality' => 'Chalco',
                'address_state' => 'Estado de México',
                'maps_url' => 'https://maps.google.com',
                'start_date' => '2024-01-10',
                'employment_status' => 'Activo',
                'photo' => null,
                'position' => 'Capturista',
                'department' => 'Recursos Humanos',
                'bank' => 'Azteca',
                'account_number' => '778899001122',
                'education_level' => 'Técnico',
                'specialty' => 'Administración',
                'contract_type' => 'Temporal',
                'seniority' => '1 año 3 meses',
                'nss' => '72345678901',
                'rfc' => 'NARR970707STU',
            ],
            [
                'first_name' => 'Diana',
                'last_name' => 'Cruz',
                'email' => 'diana.cruz@oxi.com',
                'phone' => '5589012345',
                'street' => 'Calle 6',
                'external_number' => '104',
                'internal_number' => 'H',
                'postal_code' => '09000',
                'neighborhood' => 'Xochimilco',
                'municipality' => 'Ciudad de México',
                'address_state' => 'Ciudad de México',
                'maps_url' => 'https://maps.google.com',
                'start_date' => '2022-08-18',
                'employment_status' => 'Activo',
                'photo' => null,
                'position' => 'Ejecutiva comercial',
                'department' => 'Ventas',
                'bank' => 'Banamex',
                'account_number' => '889900112233',
                'education_level' => 'Licenciatura',
                'specialty' => 'Mercadotecnia',
                'contract_type' => 'Indefinido',
                'seniority' => '3 años 8 meses',
                'nss' => '82345678901',
                'rfc' => 'CRUD980808VWX',
            ],
            [
                'first_name' => 'Jorge',
                'last_name' => 'Flores',
                'email' => 'jorge.flores@oxi.com',
                'phone' => '5590123456',
                'street' => 'Calle 7',
                'external_number' => '105',
                'internal_number' => 'I',
                'postal_code' => '09000',
                'neighborhood' => 'Naucalpan',
                'municipality' => 'Naucalpan de Juárez',
                'address_state' => 'Estado de México',
                'maps_url' => 'https://maps.google.com',
                'start_date' => '2020-05-30',
                'employment_status' => 'Inactivo',
                'photo' => null,
                'position' => 'Soporte TI',
                'department' => 'Sistemas',
                'bank' => 'BBVA',
                'account_number' => '990011223344',
                'education_level' => 'Ingeniería',
                'specialty' => 'Redes',
                'contract_type' => 'Indefinido',
                'seniority' => '5 años 11 meses',
                'nss' => '92345678901',
                'rfc' => 'FLOJ990909YZA',
            ],
            [
                'first_name' => 'Sofia',
                'last_name' => 'Herrera',
                'email' => 'sofia.herrera@oxi.com',
                'phone' => '5511122233',
                'street' => 'Calle 8',
                'external_number' => '106',
                'internal_number' => 'J',
                'postal_code' => '09000',
                'neighborhood' => 'Cuautitlán',
                'municipality' => 'Cuautitlán',
                'address_state' => 'Estado de México',
                'maps_url' => 'https://maps.google.com',
                'start_date' => '2023-07-14',
                'employment_status' => 'Activo',
                'photo' => null,
                'position' => 'Asistente de ventas',
                'department' => 'Ventas',
                'bank' => 'Santander',
                'account_number' => '101112131415',
                'education_level' => 'Licenciatura',
                'specialty' => 'Comercio',
                'contract_type' => 'Temporal',
                'seniority' => '1 año 9 meses',
                'nss' => '10345678901',
                'rfc' => 'HERS000101BCD',
            ],
        ];

        foreach ($employees as $employee) {
            $position = Position::query()
                ->where('name', $employee['position'])
                ->whereHas('department', fn ($query) => $query->where('name', $employee['department']))
                ->firstOrFail();

            unset($employee['position'], $employee['department']);
            $employee['position_id'] = $position->id;

            Employee::updateOrCreate(
                ['email' => $employee['email']],
                $employee
            );
        }
    }
}
