export function getGeneralPurchaseSourceOrdersTableConfig() {
    return {
        columns: [
            {
                key: 'folio',
                label: 'Orden de compra',
                width: '175px',
                mobileSecondary: false,
            },
            {
                key: 'requested_by_name',
                label: 'Solicitado por',
                mobileLabel: 'Solicitado por',
                mobileDisplay: true,
            },
            {
                key: 'review_status_label',
                label: 'Estado',
                format: 'badge',
                formatOptions: {
                    statusMap: {
                        Pendiente: 'amber',
                        Aprobada: 'green',
                        Rechazada: 'red',
                    },
                },
                mobileLabel: 'Estado',
                mobileDisplay: true,
            },
            {
                key: 'items_count',
                label: 'Productos',
                format: 'number',
                mobileLabel: 'Productos',
                mobileDisplay: true,
            },
            {
                key: 'requested_quantity',
                label: 'Piezas',
                format: 'number',
                mobileLabel: 'Piezas',
                mobileDisplay: true,
            },
            {
                key: 'generated_at',
                label: 'Fecha',
                format: 'date',
                mobileLabel: 'Fecha',
                mobileDisplay: true,
            },
        ],
        actions: [
            {
                id: 'view',
                label: 'Ver',
                icon: 'visibility',
                variant: 'blue',
                permission: 'inventory.purchase-orders.source.view',
            },
            {
                id: 'approve',
                label: 'Aprobar',
                icon: 'check_circle',
                variant: 'green',
                permission: 'inventory.purchase-orders.source.review',
                hidden: (row) => row.review_status === 'APPROVED' || row.selected || row.in_draft,
            },
            {
                id: 'reject',
                label: 'Rechazar',
                icon: 'cancel',
                variant: 'red',
                permission: 'inventory.purchase-orders.source.review',
                hidden: (row) => row.review_status === 'REJECTED' || row.selected || row.in_draft,
            },
            {
                id: 'transfer',
                label: 'Transferir',
                icon: 'swap_horiz',
                variant: 'secondary',
                permission: 'inventory.purchase-orders.source.transfer',
                hidden: (row) => row.review_status !== 'APPROVED' || row.selected || row.in_draft,
            },
            {
                id: 'edit',
                label: 'Editar',
                icon: 'edit',
                variant: 'yellow',
                permission: 'inventory.purchase-orders.source.update',
                hidden: (row) => row.selected || row.in_draft,
            },
            {
                id: 'history',
                label: 'Historial de transferencias',
                icon: 'history',
                variant: 'blue',
                permission: 'inventory.purchase-orders.source.view',
                hidden: (row) => Number(row.transfer_history_count || 0) === 0,
            },
            {
                id: 'add',
                label: 'Agregar a Orden de compra general',
                icon: 'add_circle',
                variant: 'green',
                permission: 'inventory.purchase-orders.general.create',
                hidden: (row) => row.review_status !== 'APPROVED' || row.selected,
            },
            {
                id: 'remove',
                label: 'Quitar de Orden de compra general',
                icon: 'remove_circle',
                variant: 'red',
                permission: 'inventory.purchase-orders.general.create',
                hidden: (row) => !row.selected,
            },
        ],
        mobileCardHeaderField: 'folio',
        noDataMessage: 'Esta sucursal no tiene órdenes pendientes asignadas.',
        rowKey: 'id',
        hoverEffect: true,
    }
}
