export const inventoryMovementReportTableConfig = {
    columns: [
        {
            key: 'code',
            label: 'Codigo',
            format: 'text',
            mobileLabel: 'Codigo',
            mobileDisplay: true,
            width: '160px',
        },
        {
            key: 'product',
            label: 'Nombre producto',
            format: 'text',
            mobileLabel: 'Nombre producto',
            mobileSecondary: true,
            width: '260px',
        },
        {
            key: 'department',
            label: 'Departamento',
            format: 'text',
            mobileLabel: 'Departamento',
            mobileDisplay: true,
            fallback: 'Sin departamento',
        },
        {
            key: 'category',
            label: 'Categoria',
            format: 'text',
            mobileLabel: 'Categoria',
            mobileDisplay: true,
            fallback: 'Sin categoria',
        },
        {
            key: 'lot_number',
            label: 'Lote',
            format: 'text',
            mobileLabel: 'Lote',
            mobileDisplay: true,
        },
        {
            key: 'user',
            label: 'Usuario',
            format: 'text',
            mobileLabel: 'Usuario',
            mobileDisplay: true,
            width: '220px',
            cellClass: 'max-w-[220px]',
        },
        {
            key: 'status_label',
            label: 'Tipo de movimiento',
            format: 'badge',
            formatOptions: {
                statusMap: {
                    Entrada: 'green',
                    Salida: 'red',
                    Ajuste: 'blue',
                },
            },
            mobileLabel: 'Tipo de movimiento',
            mobileBadge: true,
        },
        {
            key: 'movement_reason_label',
            label: 'Motivo',
            format: 'text',
            mobileLabel: 'Motivo',
            mobileDisplay: true,
        },
        {
            key: 'quantity',
            label: 'Cantidad',
            format: 'number',
            formatOptions: { unitKey: 'inventory_unit' },
            mobileLabel: 'Cantidad',
            mobileDisplay: true,
        },
        {
            key: 'movement_date',
            label: 'Fecha',
            format: 'date',
            mobileLabel: 'Fecha',
            mobileDisplay: true,
        },
        {
            key: 'notes',
            label: 'Notas',
            format: 'text',
            mobileLabel: 'Notas',
            mobileDisplay: true,
            width: '300px',
            cellClass: 'max-w-[300px]',
        },
    ],

    actions: [],
    mobileCardHeaderField: 'product',
    noDataMessage: 'No hay movimientos que coincidan con los filtros aplicados',
    rowKey: 'id',
    hoverEffect: true,
}
