export const inventoryReportTableConfig = {
    columns: [
        {
            key: "product",
            label: "Producto",
            format: "text",
            mobileLabel: "Producto",
            mobileSecondary: true,
            width: "260px",
        },
        {
            key: "category",
            label: "Categoría",
            format: "text",
            mobileLabel: "Categoría",
            mobileDisplay: true,
        },
        {
            key: "lot_number",
            label: "Lote",
            format: "text",
            mobileLabel: "Lote",
            mobileDisplay: true,
        },
        {
            key: "status_label",
            label: "Estado",
            format: "badge",
            formatOptions: {
                statusMap: {
                    Caducado: "red",
                    "Próximo a caducar": "amber",
                    Vigente: "green",
                    Agotado: "red",
                    "Stock bajo": "amber",
                    "Con lotes caducados": "red",
                    "Con lotes por vencer": "amber",
                    "Sin movimiento reciente": "slate",
                    "Sin movimiento": "slate",
                    "Rotación baja": "amber",
                    "Rotación media": "blue",
                    "Rotación alta": "green",
                },
            },
            mobileLabel: "Estado",
            mobileBadge: true,
        },
        {
            key: "quantity",
            label: "Cantidad",
            format: "number",
            mobileLabel: "Cantidad",
            mobileDisplay: true,
        },
        {
            key: "initial_quantity",
            label: "Cantidad inicial",
            format: "number",
        },
        {
            key: "expiration_date",
            label: "Caducidad",
            format: "date",
            mobileLabel: "Caducidad",
            mobileDisplay: true,
        },
        {
            key: "days",
            label: "Días",
            format: "number",
            mobileLabel: "Días",
            mobileDisplay: true,
        },
        {
            key: "received_at",
            label: "Ingreso lote",
            format: "date",
        },
        {
            key: "last_entry_at",
            label: "Última entrada",
            format: "date",
        },
        {
            key: "current_stock",
            label: "Stock actual",
            format: "number",
        },
        {
            key: "min_stock",
            label: "Stock mínimo",
            format: "number",
        },
        {
            key: "estimated_loss",
            label: "Impacto estimado",
            format: "currency",
        },
    ],

    actions: [],
    mobileCardHeaderField: "product",
    noDataMessage: "No hay lotes que coincidan con los filtros aplicados",
    rowKey: "id",
    striped: true,
    hoverEffect: true,
};
