export const inventoryReportTableConfig = {
    columns: [
        {
            key: 'code',
            label: 'Codigo',
            format: 'text',
            mobileLabel: 'Codigo',
            mobileDisplay: true,
            width: '160px',
        },
        {
            key: 'product',
            label: 'Nombre Producto',
            format: 'text',
            mobileLabel: 'Nombre Producto',
            mobileSecondary: true,
            width: '260px',
        },
        {
            key: 'department',
            label: 'Departamento',
            format: 'text',
            mobileLabel: 'Departamento',
            mobileDisplay: true,
            fallback: 'Sin departamento',
        },
        {
            key: 'category',
            label: 'Categoria',
            format: 'text',
            mobileLabel: 'Categoria',
            mobileDisplay: true,
            fallback: 'Sin categoria',
        },
        {
            key: 'status_label',
            label: 'Estado',
            format: 'badge',
            formatOptions: {
                statusMap: {
                    Caducado: 'red',
                    'Proximo a caducar': 'amber',
                    Vigente: 'green',
                    Agotado: 'red',
                    'Stock bajo': 'amber',
                    'Con lotes caducados': 'red',
                    'Con lotes por vencer': 'amber',
                    'Sin movimiento reciente': 'slate',
                    'Sin movimiento': 'slate',
                    'Rotacion baja': 'amber',
                    'Rotacion media': 'blue',
                    'Rotacion alta': 'green',
                },
            },
            mobileLabel: 'Estado',
            mobileBadge: true,
        },
        {
            key: 'lot_number',
            label: 'Lote',
            format: 'text',
            mobileLabel: 'Lote',
            mobileDisplay: true,
        },
        {
            key: 'received_at',
            label: 'Fecha Ingreso',
            format: 'date',
            mobileLabel: 'Fecha Ingreso',
            mobileDisplay: true,
        },
        {
            key: 'expiration_date',
            label: 'Fecha Caducidad',
            format: 'date',
            mobileLabel: 'Fecha Caducidad',
            mobileDisplay: true,
        },
        {
            key: 'estimated_loss',
            label: 'Impacto de perdida',
            format: 'currency',
            mobileLabel: 'Impacto de perdida',
            mobileDisplay: true,
        },
    ],

    actions: [],
    mobileCardHeaderField: 'product',
    noDataMessage: 'No hay lotes que coincidan con los filtros aplicados',
    rowKey: 'id',
    hoverEffect: true,
}
