export const movementsReportTableConfig = {
    columns: [
        {
            key: "date",
            label: "Fecha",
            format: "text",
            width: "10%",
            mobileLabel: "Fecha",
            fallback: "Sin fecha",
        },
        {
            key: "time",
            label: "Hora",
            format: "text",
            width: "8%",
            mobileDisplay: false,
            fallback: "--:--",
        },
        {
            key: "product",
            label: "Producto",
            format: "text",
            width: "22%",
            mobileSecondary: true,
            fallback: "Sin producto",
        },
        {
            key: "user",
            label: "Usuario",
            format: "text",
            width: "14%",
            mobileLabel: "Usuario",
            fallback: "Sistema",
        },
        {
            key: "type",
            label: "Tipo",
            format: "badge",
            width: "11%",
            formatOptions: {
                statusMap: {
                    IN: "green",
                    OUT: "red",
                    ADJUSTMENT: "blue",
                },
            },
            mobileBadge: true,
            fallback: "N/A",
        },
        {
            key: "reason",
            label: "Motivo",
            format: "text",
            width: "15%",
            mobileDisplay: false,
            fallback: "Sin motivo",
        },
        {
            key: "quantity",
            label: "Cantidad",
            format: "text",
            width: "10%",
            mobileLabel: "Cantidad",
            fallback: "0",
            subKey: "stock_change_label",
        },
        {
            key: "new_stock",
            label: "Stock final",
            format: "text",
            width: "10%",
            mobileLabel: "Stock final",
            fallback: "0",
        },
    ],

    actions: [],

    mobileCardHeaderField: "product",
    noDataMessage: "No se encontraron movimientos.",
    rowKey: "id",
};
