export const physicalCountTableConfig = {
    columns: [
        {
            key: "name",
            label: "Nombre",
            format: "text",
            mobileLabel: "Nombre",
            mobileDisplay: true,
        },
        {
            key: "folio",
            label: "Folio",
            format: "text",
            mobileLabel: "Folio",
            mobileDisplay: true,
            fallback: "Sin folio",
        },
        {
            key: "current_round_number",
            label: "Ronda",
            format: "number",
            mobileLabel: "Ronda",
            mobileDisplay: true,
            fallback: "1",
        },
        {
            key: "status",
            label: "Estado",
            format: "badge",
            mobileLabel: "Estado",
            mobileDisplay: true,
            formatOptions: {
                labelMap: {
                    open: "Abierto",
                    closed: "Cerrado",
                    finalized: "Finalizado",
                    applied: "Aplicado",
                },
                statusMap: {
                    open: "green",
                    closed: "slate",
                    finalized: "indigo",
                    applied: "blue",
                },
                colorMap: {
                    open: "green",
                    closed: "slate",
                    finalized: "indigo",
                    applied: "blue",
                },
            },
        },
    ],

    actions: [
        {
            id: "open",
            label: "Ingresar a auditoría",
            icon: "login",
            variant: "blue",
            permission: "audits.physical-counts.count",
        },
        {
            id: "close",
            label: "Cerrar auditoría",
            icon: "lock",
            variant: "amber",
            permission: "audits.physical-counts.close",
            hidden: (item) => item.status !== "open",
        },
        {
            id: "reopen",
            label: "Reabrir auditoría",
            icon: "restart_alt",
            variant: "green",
            permission: "audits.physical-counts.reopen",
            hidden: (item) => item.status !== "closed",
        },
        {
            id: "finalize",
            label: "Finalizar auditoría",
            icon: "verified",
            variant: "indigo",
            permission: "audits.physical-counts.finalize",
            hidden: (item) => item.status !== "closed",
        },
        {
            id: "participants",
            label: "Participantes",
            icon: "group_add",
            variant: "indigo",
            permission: "audits.physical-counts.participants",
        },
        {
            id: "apply",
            label: "Aplicar ajustes",
            icon: "check_circle",
            variant: "green",
            permission: "audits.physical-counts.apply",
            hidden: (item) => item.status !== "finalized",
        },
        {
            id: "delete",
            label: "Eliminar auditoría",
            icon: "delete",
            variant: "red",
            permission: "audits.physical-counts.delete",
            hidden: (item) => item.status !== "open",
        },
    ],

    mobileCardHeaderField: "name",
    noDataMessage: "Todavía no hay conteos físicos creados.",
}
