export const rotationReportTableConfig = {
    columns: [
        {
            key: "product",
            label: "Producto",
            format: "text",
            width: "25%",
            mobileSecondary: true,
            fallback: "Sin producto",
        },
        {
            key: "category",
            label: "Categoría",
            format: "text",
            width: "16%",
            mobileDisplay: false,
            fallback: "Sin categoría",
        },
        {
            key: "stock",
            label: "Stock",
            format: "text",
            width: "10%",
            mobileLabel: "Stock",
            fallback: "0",
            subKey: "min_stock_label",
        },
        {
            key: "total_out",
            label: "Salidas",
            format: "text",
            width: "10%",
            mobileLabel: "Salidas",
            fallback: "0",
        },
        {
            key: "last_out_at",
            label: "Última salida",
            format: "text",
            width: "13%",
            mobileLabel: "Última salida",
            fallback: "Sin salida",
        },
        {
            key: "days_without_movement",
            label: "Días sin movimiento",
            format: "text",
            width: "13%",
            mobileDisplay: false,
            fallback: "-",
        },
        {
            key: "rotation_level",
            label: "Rotación",
            format: "badge",
            width: "13%",
            formatOptions: {
                statusMap: {
                    HIGH: "green",
                    MEDIUM: "blue",
                    LOW: "amber",
                    NO_MOVEMENT: "red",
                },
            },
            mobileBadge: true,
            fallback: "N/A",
        },
    ],

    actions: [],

    mobileCardHeaderField: "product",
    noDataMessage: "No hay información de rotación para mostrar.",
    rowKey: "branch_product_id",
};
