export function getInventoryMovementReportToolbarConfig({
    filters,
    categories = [],
    users = [],
    movementTypes = [],
    movementReasons = [],
} = {}) {
    return {
        icon: 'swap_horiz',
        title: 'Reportes de movimientos',
        subtitle: 'Consulta entradas, salidas, ajustes y trazabilidad por lote.',
        backButton: true,
        backLabel: 'Sucursales',
        search: filters?.search ?? '',
        searchPlaceholder: 'Buscar producto, codigo, lote, usuario o nota...',
        showSearch: true,
        showRecordsPerPage: true,
        showCounter: false,
        filters: [
            {
                key: 'categoryId',
                label: 'Categoría',
                placeholder: 'Todas las categorías',
                value: filters?.categoryId ?? '',
                options: categories,
                optionLabel: 'name',
                optionValue: 'id',
            },
            {
                key: 'userId',
                label: 'Usuario',
                placeholder: 'Todos los usuarios',
                value: filters?.userId ?? '',
                options: users,
                optionLabel: 'name',
                optionValue: 'id',
            },
            {
                key: 'movementType',
                label: 'Tipo movimiento',
                placeholder: 'Todos los tipos',
                value: filters?.movementType ?? '',
                options: movementTypes,
                optionLabel: 'label',
                optionValue: 'id',
            },
            {
                key: 'movementReason',
                label: 'Motivo',
                placeholder: 'Todos los motivos',
                value: filters?.movementReason ?? '',
                options: movementReasons,
                optionLabel: 'label',
                optionValue: 'id',
            },
            {
                key: 'dateFrom',
                label: 'Inicio',
                type: 'date',
                value: filters?.dateFrom ?? '',
            },
            {
                key: 'dateTo',
                label: 'Fin',
                type: 'date',
                value: filters?.dateTo ?? '',
            },
            {
                key: 'search',
                visible: false,
                label: 'Búsqueda',
                type: 'text',
                field: 'toolbar_search',
                placeholder: 'Producto, código, lote, usuario o nota...',
                value: filters?.search ?? '',
            },
        ],
        actions: [
            {
                id: 'clear',
                label: 'Limpiar',
                icon: 'restart_alt',
                variant: 'slate',
            },
            {
                id: 'excel',
                label: 'Excel',
                icon: 'table_view',
                variant: 'green',
                permission: 'reports.movements.export.excel',
            },
            {
                id: 'pdf',
                label: 'PDF',
                icon: 'picture_as_pdf',
                variant: 'red',
                permission: 'reports.movements.export.pdf',
            },
        ],
        tabs: [],
    }
}
